apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
spec:
  ports:
  - port: 80
    targetPort: metrics-port
    name: "metrics-port"
  - port: 81
    targetPort: push-port
    name: "push-port"
  selector:
    name: fluentd
  type: NodePort
